### ISSUE TITLE
1.0 nm padding for cubic system significantly larger number of atoms compared to other engines

### ISSUE THREAD

**Issue by blakemertz** [openmm/openmm-setup#40]
I am placing a largish protein (11k atoms, 800+ residues) in a cubic water box. The protein was initially oriented along its principal axes to make it fit more efficiently in the water box. I used openmm-setup with a 1.0 nm padding to solvate the protein and came up with a system of 148k atoms. I then used the solvate plugin in VMD with 1.0 nm padding and ended up with 70k atoms. Both are using the same water model (TIP3P) and the same orientation of the protein. I know that there were some modifications made to addSolvent for the 8.0 release, but this is a drastic difference between the two solvation approaches. Below are the dimensions for the two boxes:
```
measure minmax $openmm
{-64.80699920654297 -56.0989990234375 -20.85700035095215} {52.176998138427734 61.305999755859375 96.37899780273438}
>Main< (4GL2-homology) 4 % measure minmax $vmd
{-44.362998962402344 -43.792999267578125 -17.31100082397461} {31.85099983215332 48.965999603271484 92.9520034790039}
```
Besides choosing an orthorhombic periodic system, is there any other way to optimize the addSolvent step? Trying to avoid taking a big performance hit in my simulations.

**Comment by peastman** [comment]
See the [API documentation for `addSolvent()`](http://docs.openmm.org/latest/api-python/generated/openmm.app.modeller.Modeller.html#openmm.app.modeller.Modeller.addSolvent).  There are lots of different ways you can specify the box size.  If you use the `padding` option, it finds a bounding sphere that fully contains the solute and adds padding around it.  This guarantees the solute will never collide with itself *no matter how it rotates during the simulation*.  If you're certain the protein isn't going to rotate (for example, if you're applying restraints to it), you can use a smaller box around the optimized orientation.  In that case, `boxSize` is probably the option you want to use.  But only do that if you're certain the protein won't rotate!  Otherwise it could end up colliding with itself part way through the simulation.

**Comment by blakemertz** [comment]
@peastman thanks for the quick reply and explanation. I will be doing short timescale runs (< 4 ns), so i don't anticipate having noticeable rotation of the protein of interest.

**Comment by peastman** [comment]
You should monitor the rotation to be sure.  4 ns isn't all that short, and significant rotation can happen in that time.  Make sure no atom in one periodic copy ever comes too close to any atom in another periodic copy.

**Comment by blakemertz** [comment]
I will definitely do that. If I observe significant rotation I will add some restraints to the protein to avoid that issue.
